version: '3.8'

services:
    app:
        build: .
        container_name: symfony_app
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - symfony
        environment:
            DATABASE_URL: mysql://symfony:symfony@db:3306/symfony

    web:
        image: nginx:alpine
        container_name: symfony_web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - symfony

    db:
        image: mysql:8.0
        container_name: symfony_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - "3306:3306"
        networks:
            - symfony

networks:
    symfony:
