apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony
  template:
    metadata:
      labels:
        app: symfony
    spec:
      containers:
        - name: symfony
          image: ghcr.io/sazibsust10/symfony-demo:1.0.0
          imagePullPolicy: IfNotPresent
          command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL