apiVersion: v1
kind: Service
metadata:
  name: symfony-demo
  labels:
    app: symfony-demo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: symfony-demo
