apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-app
  template:
    metadata:
      labels:
        app: symfony-app
    spec:
      initContainers:
        - name: copy-symfony-code
          image: ghcr.io/sazibsust10/symfony-demo:1.0.0
          command: ['sh', '-c', 'cp -a /var/www/html/* /symfony-code/']
          volumeMounts:
            - name: symfony-code
              mountPath: /symfony-code
      containers:
        - name: symfony
          image: ghcr.io/sazibsust10/symfony-demo:1.0.0
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: symfony-db-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: symfony-code       # Changed from app-code to symfony-code
              mountPath: /var/www/html
      volumes:
        - name: symfony-code          # Changed from app-code to symfony-code
          persistentVolumeClaim:
            claimName: symfony-pvc
