apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-app
  template:
    metadata:
      labels:
        app: symfony-app
    spec:
      initContainers:
        - name: copy-symfony-code
          image: ghcr.io/sazibsust10/symfony-demo:2.0.0
          command: ['sh', '-c', 'cp -a /var/www/html/* /symfony-code/'] # Copying code to a shared volume
          volumeMounts:
            - name: symfony-code
              mountPath: /symfony-code
      containers:
        - name: symfony
          image: ghcr.io/sazibsust10/symfony-demo:2.0.0
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: symfony-db-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: symfony-code       # Changed from app-code to symfony-code
              mountPath: /var/www/html
          # resources: # Uncomment and adjust resource requests and limits as needed
          #   requests:
          #     memory: "256Mi" 
          #     cpu: "250m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
          # livenessProbe: # We need to have /health route in the app which is missing. we need to create a health check route in the Symfony app
          #   httpGet:
          #     path: /health
          #     port: 9000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 9000
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
      volumes:
        - name: symfony-code          # Changed from app-code to symfony-code
          persistentVolumeClaim:
            claimName: symfony-pvc
