apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-web
  template:
    metadata:
      labels:
        app: symfony-web
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          command: ["nginx"]
          args: ["-g", "daemon off;"]
          ports:
            - containerPort: 80  # Nginx listens on port 80 by default
          volumeMounts:
            - name: symfony-code
              mountPath: /var/www/html  # This should match the Nginx config's root path
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: symfony-code
          persistentVolumeClaim:
            claimName: symfony-pvc
        - name: nginx-config
          configMap:
            name: nginx-config  # Match the actual ConfigMap name
