apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/sazibsust10/symfony-demo
    # newName: ghcr.io/sazibsust10/symfony-demo
    newTag: 2.0.1
resources:
  - secrets/secret.yaml
  - config/configmap.yaml
  - storage/symfony-pvc.yaml
  - deployments/mysql-deployment.yaml
  - jobs/db-migrate.yaml
  - deployments/app-deployment.yaml
  - deployments/web-deployment.yaml
  - services/app-service.yaml
  - services/db-service.yaml
  - services/web-service.yaml
  - autoscaling/hpa.yaml
  