apiVersion: v1
kind: Secret
metadata:
  name: symfony-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: symfony
  MYSQL_USER: symfony
  MYSQL_PASSWORD: symfony
  DATABASE_URL: mysql://symfony:symfony@db:3306/symfony

