apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symfony-pvc
spec:
  accessModes:
    - ReadWriteOnce          
  resources:
    requests:
      storage: 1Gi
  # Optional: remove if unsure or cluster has no `standard` class
  storageClassName: standard

