apiVersion: v1
kind: Secret
metadata:
  name: symfony-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: symfony
  MYSQL_USER: symfony
  MYSQL_PASSWORD: symfony
  DATABASE_URL: mysql://symfony:symfony@db:3306/symfony

# apiVersion: v1
# kind: Secret
# metadata:
#   name: symfony-db-secret
# type: Opaque
# data:
#   MYSQL_ROOT_PASSWORD: cm9vdA==              
#   MYSQL_DATABASE: c3ltZm9ueQ==              
#   MYSQL_USER: c3ltZm9ueQ==                  
#   MYSQL_PASSWORD: c3ltZm9ueQ==             
#   DATABASE_URL: bXlzcWw6Ly9zeW1mb255OnN5bWZvbnlAZGI6MzMwNi9zeW1mb255