apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/sazibsust10/symfony-demo
    # newName: ghcr.io/sazibsust10/symfony-demo
    newTag: 2.0.0
resources:
  - ../../base